### ISSUE TITLE
'IndexError: list index out of range' when loading page and putting in value for lo rate field

### ISSUE THREAD

**Issue by eliaahadi** [tum-lkn/tcgui#3]
Hi, I'm currently trying to use this app but ran into issue when putting in ```Rate``` value of 6 or higher with ```lo``` field just to test and it returns an error. I'm fairly new to network tests so I apologize if this an easy question.

I tried to reload server but it seems to store that value and not let me see the original page.

Any thoughts? Thank you. 
Here is the error below:
```
~/tcgui$ sudo python3 main.py
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2019-03-20 18:02:00,469] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/gitai/.local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gitai/.local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gitai/.local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gitai/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/gitai/.local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gitai/.local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 26, in main
    rules = get_active_rules()
  File "main.py", line 93, in get_active_rules
    rule = parse_rule(arguments)
  File "main.py", line 129, in parse_rule
    if 'ms' in split_rule[i + 2]:
IndexError: list index out of range
127.0.0.1 - - [20/Mar/2019 18:02:00] "GET / HTTP/1.1" 500 -
``` 

And screenshot of website:
![image](https://user-images.githubusercontent.com/9751505/54672460-6a4b8a80-4b3b-11e9-90d2-b969011452d5.png)

**Comment by csieber** [comment]
The issue should be fixed now. Thanks for pointing it out!

**Comment by eliaahadi** [comment]
Great thank you! It is fixed. I have a new issue now which I'll file.
